#ifndef LOGOS_WITNESS_UI_QML_PLUGIN_H
#define LOGOS_WITNESS_UI_QML_PLUGIN_H

#include <QByteArray>
#include <QString>
#include <QVariantList>
#include <QVariantMap>
#include "logos_witness_ui_qml_interface.h"
#include "LogosViewPluginBase.h"
#include "rep_logos_witness_ui_qml_source.h"

class LogosAPI;
class LogosModules;
class QTimer;

// UI module backend. Hybrid `ui_qml + C++ backend` plugin.
//
// Every cross-module call goes through the typed `m_logos->X.Y(...)`
// accessor on the backend's own thread — the documented
// module-to-module path per the logos-tutorial cpp-ui-app guide and
// the storage/delivery journey docs (logos-co/logos-docs PR #226,
// PR #166), and the shape the reference apps (logos-chat-ui,
// logos-accounts-ui) use. No worker threads, no nested event loops:
// the SDK's LogosAPIClient is single-threaded, so calls stay on the
// thread that owns it.
class LogosWitnessUiQmlPlugin : public LogosWitnessUiQmlSimpleSource,
                                public LogosWitnessUiQmlInterface,
                                public LogosWitnessUiQmlViewPluginBase
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID LogosWitnessUiQmlInterface_iid FILE "metadata.json")
    Q_INTERFACES(LogosWitnessUiQmlInterface)

public:
    explicit LogosWitnessUiQmlPlugin(QObject* parent = nullptr);
    ~LogosWitnessUiQmlPlugin() override;

    QString name()    const override { return "logos_witness_ui_qml"; }
    QString version() const override { return "0.1.0"; }

    Q_INVOKABLE void initLogos(LogosAPI* api);

    // SLOTs from .rep — override the generated virtuals
    void submitPhotoAsync(QString localId, QString filePath, QString timestamp, QString geohash) override;
    void fetchPhotoAsync(QString cid) override;
    QVariantMap decodeGeohash(QString geohash) override;
    QString loadLocalPhotoUrl(QString filePath) override;

private slots:
    // 5 s polling Timer. Pulls a fresh refs list from core +
    // re-checks delivery readiness, pushes both into the auto-syncing
    // PROPs (setRefs / setDeliveryReady — generated by repc).
    void _refreshFromCore();

private:
    // Write `bytes` into the plugin's preview-cache/ dir under the
    // given key (callers pick: SHA-256 prefix for local picks, CID
    // for storage fetches), with the given file suffix (sans dot),
    // and return a `file://` URL the QML engine's interceptor will
    // accept. On any I/O failure returns a string starting with
    // "error:" — callers branch on that prefix.
    QString _cacheBytesUnderPluginDir(const QByteArray& bytes,
                                       const QString& key,
                                       const QString& suffix);

    // No separate m_logosAPI: initLogos assigns the inherited
    // PluginInterface::logosAPI field and uses it as the init-guard.
    LogosModules* m_logos = nullptr;
    QTimer* m_refreshTimer = nullptr;
};

#endif // LOGOS_WITNESS_UI_QML_PLUGIN_H
