#ifndef LOGOS_WITNESS_UI_QML_PLUGIN_H
#define LOGOS_WITNESS_UI_QML_PLUGIN_H

#include <QByteArray>
#include <QHash>
#include <QString>
#include <QVariantList>
#include <QVariantMap>
#include "logos_witness_ui_qml_interface.h"
#include "LogosViewPluginBase.h"
#include "rep_logos_witness_ui_qml_source.h"

class LogosAPI;
class LogosAPIClient;
class LogosModules;
class LogosObject;
class QTimer;

// UI module backend. Owns every blocking core call so the QML render
// thread never invokes logos.callModule directly (basecamp's bridge is
// sync-only — a single sync call freezes the UI for the duration of the
// upstream RPC). Async ops post onto QThreadPool, return via paired
// SIGNALs declared in `src/logos_witness_ui_qml.rep`.
class LogosWitnessUiQmlPlugin : public LogosWitnessUiQmlSimpleSource,
                                public LogosWitnessUiQmlInterface,
                                public LogosWitnessUiQmlViewPluginBase
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID LogosWitnessUiQmlInterface_iid FILE "metadata.json")
    Q_INTERFACES(LogosWitnessUiQmlInterface)

public:
    explicit LogosWitnessUiQmlPlugin(QObject* parent = nullptr);
    ~LogosWitnessUiQmlPlugin() override;

    QString name()    const override { return "logos_witness_ui_qml"; }
    QString version() const override { return "0.1.0"; }

    Q_INVOKABLE void initLogos(LogosAPI* api);

    // SLOTs from .rep — override the generated virtuals
    void submitPhotoAsync(QString localId, QString filePath, QString timestamp, QString geohash) override;
    void fetchPhotoAsync(QString cid) override;
    QVariantMap decodeGeohash(QString geohash) override;
    QString loadLocalPhotoUrl(QString filePath) override;

private slots:
    // Driven by a 5 s QTimer. Pulls a fresh refs list from core +
    // re-checks delivery readiness, pushes both into the auto-syncing
    // PROPs (setRefs / setDeliveryReady — generated by repc).
    void _refreshFromCore();

private:
    // Called once from initLogos to wire core's `referenceObserved`
    // event so we get a push update when peers (or our own submits)
    // produce a new ref. Falls back gracefully if the wiring fails —
    // the 5 s poll covers the same ground.
    void _subscribeToCoreEvents();

    // Invoked from worker threads to publish results. Reposts onto
    // the backend thread via QueuedConnection.
    void _emitSubmitDone(QString localId, QString contentHash, QString storageCid,
                         bool ok, bool deliveryOk, QString error);
    void _emitPhotoReady(QString cid, QByteArray bytes);
    void _emitPhotoFailed(QString cid, QString error);

    // Core RPC helpers. Synchronous; only call from worker threads or
    // the refresh timer (NOT from initLogos — that runs on the
    // ui-host main thread and would block startup the same way QML
    // does).
    QVariantMap _coreCall(const QString& method, const QVariantList& args);
    QVariantList _coreCallList(const QString& method, const QVariantList& args);

    LogosAPI* m_logosAPI = nullptr;
    LogosModules* m_logos = nullptr;
    LogosAPIClient* m_coreClient = nullptr;  // cached client for "logos_witness_core"
    LogosObject* m_coreObject = nullptr;     // handle for event subscription
    QTimer* m_refreshTimer = nullptr;
};

#endif // LOGOS_WITNESS_UI_QML_PLUGIN_H
