#ifndef LOGOS_WITNESS_UI_QML_PLUGIN_H
#define LOGOS_WITNESS_UI_QML_PLUGIN_H

#include <QByteArray>
#include <QHash>
#include <QString>
#include <QVariantList>
#include <QVariantMap>
#include "logos_witness_ui_qml_interface.h"
#include "LogosViewPluginBase.h"
#include "rep_logos_witness_ui_qml_source.h"

class LogosAPI;
class LogosAPIClient;
class LogosModules;
class LogosObject;
class QTimer;

// UI module backend. Owns every blocking core call so the QML render
// thread never invokes logos.callModule directly (basecamp's bridge is
// sync-only — a single sync call freezes the UI for the duration of the
// upstream RPC). Async ops post onto QThreadPool, return via paired
// SIGNALs declared in `src/logos_witness_ui_qml.rep`.
class LogosWitnessUiQmlPlugin : public LogosWitnessUiQmlSimpleSource,
                                public LogosWitnessUiQmlInterface,
                                public LogosWitnessUiQmlViewPluginBase
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID LogosWitnessUiQmlInterface_iid FILE "metadata.json")
    Q_INTERFACES(LogosWitnessUiQmlInterface)

public:
    explicit LogosWitnessUiQmlPlugin(QObject* parent = nullptr);
    ~LogosWitnessUiQmlPlugin() override;

    QString name()    const override { return "logos_witness_ui_qml"; }
    QString version() const override { return "0.1.0"; }

    Q_INVOKABLE void initLogos(LogosAPI* api);

    // SLOTs from .rep — override the generated virtuals
    void submitPhotoAsync(QString localId, QString filePath, QString timestamp, QString geohash) override;
    void fetchPhotoAsync(QString cid) override;
    QVariantMap decodeGeohash(QString geohash) override;
    QString loadLocalPhotoUrl(QString filePath) override;

private slots:
    // Driven by a 5 s QTimer. Pulls a fresh refs list from core +
    // re-checks delivery readiness, pushes both into the auto-syncing
    // PROPs (setRefs / setDeliveryReady — generated by repc).
    void _refreshFromCore();

    // Backend-thread slot invoked by worker threads via
    // BlockingQueuedConnection so that the underlying LogosAPIClient
    // (not thread-safe) only ever runs on its owner thread. Returns
    // the raw QVariant; callers normalise via toMap()/toList().
    QVariant _invokeCoreOnBackendThread(const QString& method, const QVariantList& args);

    // Backend-thread one-shot. Called from initLogos via
    // QueuedConnection so requestObject + onEvent both touch the SDK
    // from the thread that owns it. Falls back silently to the 5 s
    // poll on failure.
    void _subscribeToCoreEvents();

private:

    // Invoked from worker threads to publish results. Reposts onto
    // the backend thread via QueuedConnection.
    void _emitSubmitDone(QString localId, QString contentHash, QString storageCid,
                         bool ok, bool deliveryOk, QString error);
    void _emitPhotoReady(QString cid, QString url);
    void _emitPhotoFailed(QString cid, QString error);

    // Write `bytes` into the plugin's preview-cache/ dir under the
    // given key (callers pick: SHA-256 prefix for local picks, CID
    // for storage fetches), with the given file suffix (sans dot),
    // and return a `file://` URL the QML engine's interceptor will
    // accept. On any I/O failure returns a string starting with
    // "error:" — callers branch on that prefix. Safe to call from
    // worker threads (only touches filesystem; no SDK state).

    QString _cacheBytesUnderPluginDir(const QByteArray& bytes,
                                       const QString& key,
                                       const QString& suffix);

    // Marshal an `m_coreClient->invokeRemoteMethod` call onto the
    // backend thread and block the caller until it returns. The
    // upstream LogosAPIClient + LogosAPIConsumer aren't thread-safe
    // (unguarded QHash writes in onEvent; nested event loop on a
    // foreign QObject in waitForSource), so every invocation must
    // serialize through the thread that owns the consumer. Workers
    // use BlockingQueuedConnection to hand the call off without
    // deadlocking the backend's own event loop.
    QVariant _invokeCoreSync(const QString& method, const QVariantList& args);

    LogosAPI* m_logosAPI = nullptr;
    LogosModules* m_logos = nullptr;
    LogosAPIClient* m_coreClient = nullptr;  // cached client for "logos_witness_core"
    LogosObject* m_coreObject = nullptr;     // handle for event subscription
    QTimer* m_refreshTimer = nullptr;
};

#endif // LOGOS_WITNESS_UI_QML_PLUGIN_H
